/* -*- C++ -*- */

/*XX(  b,  _,  _,  _,  _,  _,  _,  _, BOOT)  \
  XX(  z,  _,  _,  _,  _,  _,  _,  _, CLOCK)   \
  XX(  _,  _,  z,all,  _,  _,  _,  _, LOG)     \
  XX(  _,  t,bzo,  t,bzo,  _,  _,  _, PRNG)    \
  XX(  n,  n,  n,  _,  _,  n,  _,  _, NOC)   */
#define IMAGE_HART_TASKS                       \
  /* BEG BO0 BO1 GR0 GR1 GR2 GR3 LIV TASK */   \
  XX(  _,  _,  _,zon,zon,  _,  _,  _, HACT)    \
  /* end of HUB init tasks */

// XX(  _,zon,zon,  _,  _,  _,  _,  _, HACT)
