#!/bin/bash
set -euo pipefail

# Check for -v (first arg only)
CMAKE_VERBOSITY=""
if [ $# -gt 0 ] && [ "x$1" == "-v" ]; then
    shift
    CMAKE_VERBOSITY="--verbose"
fi

# Define build directories
PRIMARY_BUILD_DIR="build_cross"
HOST_BUILD_DIR="build_host" # For the pip build, this will be temporary
TOOLCHAIN_FILE="srcs/cross/toolchain-cross.cmake" # Ensure this path is correct
SHARED_GENERATED_HEADERS_DIR="srcs/generated_headers" # Must match CMakeLists.txt

# Confirm we are where we expect
DIR=$(dirname $(readlink -f $0))
CUR=`pwd`
echo ${CUR}
if [ "x${CUR}" != "x${DIR}" ] ; then
    echo "ONLY RUN THIS SCRIPT FROM '${DIR}' not '${CUR}'"
    exit 2
fi

# KILL EVERYTHING IN SIGHT
if [ $# -gt 0 ] && [ "x$1" == "xnuke" ]; then
    shift
    echo -n REALCLEANING---
    rm -rf ${DIR}/${HOST_BUILD_DIR} ${DIR}/${PRIMARY_BUILD_DIR} ${DIR}/${SHARED_GENERATED_HEADERS_DIR}
    # NUKE pycaches?
    rm -rf ${DIR}/srcs/host/python/__pycache__  ${DIR}/srcs/host/python/*/__pycache__
    echo DONE
fi

# DEAL WITH OTHER ARGS?
if [ $# -gt 0 ] && [ "x$1" == "xtest" ]; then
    TESTFILE="$2"
    shift
    shift
else
    TESTFILE=""
fi

if [ $# -gt 0 ]; then
    echo "BAD ARG BAD '$1'"
    exit 3
fi

echo
echo "=== STEP 1: CONFIGURING AND BUILDING PRIMARY (CROSS) PROJECT ==="
mkdir -p "${PRIMARY_BUILD_DIR}"
cmake -S . -B "${PRIMARY_BUILD_DIR}" -DPRIMARY_CMAKE_RUNNING=1 -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
cmake --build "${PRIMARY_BUILD_DIR}" ${CMAKE_VERBOSITY}

echo ">> cmake dongo"
echo "cmake -LA -N ${PRIMARY_BUILD_DIR} | grep CANONICAL_FILE_IDS_HEADER_DIR:PATH= | cut -d'=' -f2"

# Get the canonical path to the generated FileIDs.h directory from the primary build's cache
# We need to query the cache of the *primary* build.
CANONICAL_FILE_IDS_HEADER_DIR=$(cmake -LA -N "${PRIMARY_BUILD_DIR}" | grep "CANONICAL_FILE_IDS_HEADER_DIR_CACHE:PATH=" | cut -d'=' -f2)

echo ">> cmake wongo"
echo "[${CANONICAL_FILE_IDS_HEADER_DIR}]"

if [ -z "${CANONICAL_FILE_IDS_HEADER_DIR}" ]; then
    echo "ERROR: Could not determine CANONICAL_FILE_IDS_HEADER_DIR from primary build cache."
    exit 1
fi
echo "DEBUG: Canonical FileIDs.h directory: ${CANONICAL_FILE_IDS_HEADER_DIR}"

echo
echo "= STEP 2: HOST / PYTHON BUILD (USING PIP) ="

# Define Python environment 
PYTHON_ENV_DIR="/data/ackley/PART4/code/D/blackholeSpikes/venv"
PYTHON="${PYTHON_ENV_DIR}/bin/python"
WHEELS_DIR="/data/ackley/PART4/code/D/blackholeSpikes/wheels"

# Ensure Python virtual environment exists and is activated
if [ ! -d "${PYTHON_ENV_DIR}" ]; then
    echo "XXX Create Python virtual environment at ${PYTHON_ENV_DIR}, with, e.g.:"
    echo "python3 -m venv ${PYTHON_ENV_DIR}"
    exit 2
fi
source "${PYTHON_ENV_DIR}/bin/activate"

# Build the Python package using pip, passing CMake arguments
# These arguments tell the pip-invoked CMake:
# - NOT to be the primary generator
# - WHERE to find the FileIDs.h generated by the primary build
# Note: The exact way to pass CMAKE_ARGS to pip might vary depending on your pyproject.toml
# and build backend (e.g., scikit-build, pybind11).
# This example assumes scikit-build or similar that respects CMAKE_ARGS env var.
export CMAKE_ARGS="-DPRIMARY_CMAKE_RUNNING=0 -DEXTERNAL_FILE_IDS_HEADER_DIR=${CANONICAL_FILE_IDS_HEADER_DIR}"
echo PIP CMAKE_ARGS=${CMAKE_ARGS}

# Create the wheels directory if it doesn't exist
mkdir -p "${WHEELS_DIR}"

# Run pip install
# The '.' means "build the package in the current directory"
# --no-deps is often useful to avoid pip trying to resolve dependencies from PyPI
# --no-build-isolation can prevent pip from creating its own temporary build environment,
#    but it might interfere with other aspects of your build. Test with and without.
"${PYTHON}" -m pip install ${CMAKE_VERBOSITY} --no-deps --find-links="${WHEELS_DIR}" .

echo "--- Build process complete ---"

if [ "x${TESTFILE}" != "x" ] ; then
    echo "--- Resetting before test"
    tt-smi -r
    echo "--- Running test file: ${TESTFILE}"
    ${TESTFILE}
    echo "--- Test file ${TESTFILE}: Done"
fi

