#ifndef CONSTANTS_H
#define CONSTANTS_H

/*
 * SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
 *
 * SPDX-License-Identifier: Apache-2.0
 */

//#include <fcntl.h>
#include <stdint.h>
//#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#if defined(MAP_ANON) && !defined(MAP_ANONYMOUS)
#define MAP_ANONYMOUS MAP_ANON
#endif

#define HARTNUM_B (0)
#define HARTNUM_T0 (1)
#define HARTNUM_T1 (2)
#define HARTNUM_T2 (3)
#define HARTNUM_NC (4)

#define HART_COUNT (5)

// Inlined copy of what we need from https://github.com/tenstorrent/tt-kmd/blob/main/ioctl.h:

#define TENSTORRENT_DRIVER_VERSION 2

#define TENSTORRENT_IOCTL_MAGIC 0xFA

#define TENSTORRENT_IOCTL_GET_DEVICE_INFO	_IO(TENSTORRENT_IOCTL_MAGIC, 0)
#define TENSTORRENT_IOCTL_GET_HARVESTING	_IO(TENSTORRENT_IOCTL_MAGIC, 1)
#define TENSTORRENT_IOCTL_QUERY_MAPPINGS	_IO(TENSTORRENT_IOCTL_MAGIC, 2)
#define TENSTORRENT_IOCTL_ALLOCATE_DMA_BUF	_IO(TENSTORRENT_IOCTL_MAGIC, 3)
#define TENSTORRENT_IOCTL_FREE_DMA_BUF		_IO(TENSTORRENT_IOCTL_MAGIC, 4)
#define TENSTORRENT_IOCTL_GET_DRIVER_INFO	_IO(TENSTORRENT_IOCTL_MAGIC, 5)
#define TENSTORRENT_IOCTL_RESET_DEVICE		_IO(TENSTORRENT_IOCTL_MAGIC, 6)
#define TENSTORRENT_IOCTL_PIN_PAGES		_IO(TENSTORRENT_IOCTL_MAGIC, 7)
#define TENSTORRENT_IOCTL_LOCK_CTL		_IO(TENSTORRENT_IOCTL_MAGIC, 8)
#define TENSTORRENT_IOCTL_MAP_PEER_BAR		_IO(TENSTORRENT_IOCTL_MAGIC, 9)
#define TENSTORRENT_IOCTL_UNPIN_PAGES		_IO(TENSTORRENT_IOCTL_MAGIC, 10)
#define TENSTORRENT_IOCTL_ALLOCATE_TLB		_IO(TENSTORRENT_IOCTL_MAGIC, 11)
#define TENSTORRENT_IOCTL_FREE_TLB		_IO(TENSTORRENT_IOCTL_MAGIC, 12)
#define TENSTORRENT_IOCTL_CONFIGURE_TLB		_IO(TENSTORRENT_IOCTL_MAGIC, 13)
#define TENSTORRENT_IOCTL_SET_NOC_CLEANUP		_IO(TENSTORRENT_IOCTL_MAGIC, 14)

#define TENSTORRENT_MAPPING_RESOURCE0_UC 1

#define PCI_VENDOR_ID_TENSTORRENT 0x1E52
#define PCI_DEVICE_ID_BLACKHOLE	  0xB140

#define TLB_CONFIG_ADDR         0x1FC00000
#define TLB_CONFIG_ADDR_STRIDES 0x1FC009D8
#define TLB_CONFIG_ADDR_END     0x1FC00A58

// RISCV Code entry points:

#define RISCV_DEBUG_REG_SOFT_RESET_0             0xFFB121B0
#define RISCV_DEBUG_REG_TRISC0_RESET_PC          0xFFB12228
#define RISCV_DEBUG_REG_TRISC1_RESET_PC          0xFFB1222C
#define RISCV_DEBUG_REG_TRISC2_RESET_PC          0xFFB12230
#define RISCV_DEBUG_REG_TRISC_RESET_PC_OVERRIDE  0xFFB12234
#define RISCV_DEBUG_REG_NCRISC_RESET_PC          0xFFB12238
#define RISCV_DEBUG_REG_NCRISC_RESET_PC_OVERRIDE 0xFFB1223C

#define RISCV_SOFT_RESET_B_BIT (1<<11)
#define RISCV_SOFT_RESET_T0_BIT (1<<12)
#define RISCV_SOFT_RESET_T1_BIT (1<<13)
#define RISCV_SOFT_RESET_T2_BIT (1<<14)
#define RISCV_SOFT_RESET_NC_BIT (1<<18)

#define SOFT_RESET_ALL_RISCV_EXCEPT_B (\
  RISCV_SOFT_RESET_T0_BIT |            \
  RISCV_SOFT_RESET_T1_BIT |            \
  RISCV_SOFT_RESET_T2_BIT |            \
  RISCV_SOFT_RESET_NC_BIT)

#define SOFT_RESET_ALL_RISCV (SOFT_RESET_ALL_RISCV_EXCEPT_B | RISCV_SOFT_RESET_B_BIT)

#define RISCV_DEBUG_REGS_START_ADDR 0xFFB12000

#define RISCV_DEBUG_B_PC_SNAPSHOT 0xFFB13138
#define RISCV_DEBUG_NC_PC_SNAPSHOT 0xFFB1313C
#define RISCV_DEBUG_T0_PC_SNAPSHOT 0xFFB13140
#define RISCV_DEBUG_T1_PC_SNAPSHOT 0xFFB13144
#define RISCV_DEBUG_T2_PC_SNAPSHOT 0xFFB13148

#endif /* CONSTANTS_H */
