#!/usr/bin/perl

my @l = `ps wwwaxu`;
my @hits = grep { /MFMxC4I.py/ } @l;
exit(2) if (length(@hits) != 1);
my $m = $hits[0];
exit(3) if length($m) == 0;
#print("found <$m>\n");
my @f = split(/\s+/,$m);
exit(4) if ($f[0] ne "ackley");
exit(5) unless $f[1] =~ /^\d+$/;
$pid = $f[1];
print("killing <$pid>\n");
print(kill 'HUP', $pid);
