#include "OurTLBs.h"
#include <cstring>
#include "BaseCar.h"
#include "TransportBlock.h"
#include "BHLog.h"

// use the source AHAX ?
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <errno.h>
#include "Constants.h"
#include "HostUtils.h"
#include "EWControl.h"

#include "t6-exports.h" // Generated by cross/ build

namespace MFM {

  OurTLBs::OurTLBs()
    : mDevCardNum(U32_MAX)
    , mDevFD(-1)
    , mMapAll(0)
    , mT6BufferSize(0)
    , mDMABufferPretendDeleted(false)
    , mEWsShipped(0)
    , mEWsReturned(0)
    , mEWsCommitted(0)
  {
    memset_s(mTLBInfos,0u,sizeof(mTLBInfos));
    memset_s(&mPinnedHostBuf,0u,sizeof(mPinnedHostBuf));
  }

  void OurTLBs::allocateHostRAM(size_t sizePerT6) {
    size_t size = sizePerT6 * (AHAX_TLBI_L1_LAST_UNI+1u);

    if (mDMABufferPretendDeleted) {
      // Just insist the current request is the same
      // as the pretend deleted one
      if (mT6BufferSize != sizePerT6)
        HOST_FATAL(UNSUPPORTED_OPERATION,
                   "Can't change size of host RAM per T6 (original %lu, now requested %lu)",
                   mT6BufferSize, size);
      LOGprintf(mDevCardNum,"'Reallocated' host RAM buffer\n");
      mDMABufferPretendDeleted = false;
      return;
    }
    mT6BufferSize = sizePerT6;
    pinned_host_buffer_t* buf = &mPinnedHostBuf;

    if (mT6BufferSize == 0u || buf->size != 0u)
      HOST_FATAL(ILLEGAL_ARGUMENT,"WHY ARE WE HERE");

    const u32 PAGE_SIZE = 4096;
    buf->size = ((size+PAGE_SIZE-1)/PAGE_SIZE) * PAGE_SIZE;
    LOGprintf(mDevCardNum,"Trying to allocate %lu/0x%lx (%lu + %lu) for host RAM buffer\n",
              buf->size, buf->size, mT6BufferSize, buf->size - mT6BufferSize);

    void* memory;
#if 0 // Let's just jump to the last one which is the one that works for me
    
    // Try doing a regular allocation and pinning it.
    // This should work for 4 KiB allocations, or for any size if an IOMMU is present and enabled.
    memory = mmap(NULL, buf->size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    LOGprintf(mDevCardNum,"(REGULAR) mmap returned %p\n",memory);
    {
      struct tenstorrent_pin_pages_extended pin_req;
      memset_s(&pin_req, 0, sizeof(pin_req));
      LOGprintf(mDevCardNum,"BEF pin req in.os = %u, in.flags = %u\n",pin_req.in.output_size_bytes,pin_req.in.flags);
      pin_req.in.output_size_bytes = sizeof(pin_req.out);
      pin_req.in.flags = TENSTORRENT_PIN_PAGES_NOC_DMA | TENSTORRENT_PIN_PAGES_NOC_TOP_DOWN;
      pin_req.in.size = buf->size;
      LOGprintf(mDevCardNum,"AFT pin req in.os = %u, in.flags = %u\n",pin_req.in.output_size_bytes,pin_req.in.flags);
      if (memory != MAP_FAILED) {
        pin_req.in.virtual_address = (uint64_t)(uintptr_t)memory;
        LOGprintf(mDevCardNum,"(REGULAR) IOCTL on %u\n",mDevFD);
        if (ioctl(mDevFD, TENSTORRENT_IOCTL_PIN_PAGES, &pin_req) >= 0) {
          buf->host_ptr = memory;
          buf->noc_addr = pin_req.out.noc_address;
          return;
        }
        LOGprintf(mDevCardNum,"(REGULAR) IOCTL failed: %s\n",strerror(errno));
        munmap(memory, buf->size);
      }
      // Try doing a huge page allocation and pinning it.
      // This should work for any size configured as a huge page size.
      memory = mmap(NULL, buf->size,
                    PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS |
                    MAP_HUGETLB | (__builtin_ctzll(buf->size) << MAP_HUGE_SHIFT), -1, 0);
      if (memory == MAP_FAILED) 
        LOGprintf(mDevCardNum,"(HUGE) mmap failed: %s\n",strerror(errno));
      else {
        pin_req.in.virtual_address = (uint64_t)(uintptr_t)memory;
        LOGprintf(mDevCardNum,"(HUGE) IOCTL on %u\n",mDevFD);
        if (ioctl(mDevFD, TENSTORRENT_IOCTL_PIN_PAGES, &pin_req) >= 0) {
          buf->host_ptr = memory;
          buf->noc_addr = pin_req.out.noc_address;
          return;
        }
        LOGprintf(mDevCardNum,"(HUGE) IOCTL failed: %s\n",strerror(errno));
        munmap(memory, buf->size);
      }
    }
#endif
    
    LOGprintf(mDevCardNum,"(DMA) Trying DMA allocation\n");
    // Try doing a DMA allocation.
    // This should work for any size up to the DMA buffer size limit, subject to host memory fragmentation.
    {
      struct tenstorrent_allocate_dma_buf dma_req;
      memset_s(&dma_req, 0, sizeof(dma_req));
      dma_req.in.requested_size = buf->size;
      dma_req.in.flags = TENSTORRENT_ALLOCATE_DMA_BUF_NOC_DMA;
      //LOGprintf(mDevCardNum,"(DMA) IOCTL on %u\n",mDevFD);
      if (ioctl(mDevFD, TENSTORRENT_IOCTL_ALLOCATE_DMA_BUF, &dma_req) >= 0) {
        //LOGprintf(mDevCardNum,"(DMA) MMAP for %lu\n",buf->size);
        memory = mmap(NULL, buf->size, PROT_READ | PROT_WRITE, MAP_SHARED, mDevFD, dma_req.out.mapping_offset);
        if (memory != MAP_FAILED) {
          buf->host_ptr = memory;
          buf->noc_addr = dma_req.out.noc_address;
          //LOGprintf(mDevCardNum,"(DMA) MMAP got hp %p..%p\n",(char*)memory,((char*)memory)+buf->size);
          return;
        }
        //LOGprintf(mDevCardNum,"(DMA) MMAP failed: %s\n",strerror(errno));
      } else {
        //LOGprintf(mDevCardNum,"(DMA) IOCTL failed: %s\n",strerror(errno));
      }
    }

    HOST_FATAL(UNSUPPORTED_OPERATION,"PIN FAILED");
  }

  void OurTLBs::deallocateHostRAM() {
    if (mDMABufferPretendDeleted)
      HOST_FATAL(ILLEGAL_STATE,"DMA buffer already deleted");

    LOGprintf(mDevCardNum,"(DMA) Trying to (pretend) free DMA allocation\n");
    // Free a DMA allocation.
    {
      // UMMMMMMMM. So there's not much input in the freeing DMA
      // department:
      //
      //   struct tenstorrent_free_dma_buf_in {
      //   };
      //
      // plus this passage from tt-kmd memory.c:
      //
      //      long ioctl_free_dma_buf(struct chardev_private *priv,
      //                            struct tenstorrent_free_dma_buf __user *arg)
      //    {
      //            // This is unsupported until I figure out how to block freeing as long
      //            // as a mapping exists. Otherwise the dma buffer is freed when the
      //            // struct file is destroyed, and that's safe because the mapping
      //            // refcounts the file.
      //            return -EINVAL;
      //
      // Now, do we really HAVE a struct file in this case? I guess
      // maybe we do.. ..assuming /dev/tenstorrent/X is the 'struct
      // file' in question. Do we really think it is? Let's pretend
      // yes. But still, HTF are we going to account for the DMA buf
      // still existing -- like unless the device is closed? We have
      // to maintain a secret flag or something saying whether we've
      // 'pretend deleted the dma mapping'? And only clear that flag
      // when we reach closed?

      mDMABufferPretendDeleted = true;
    }
  }

  void OurTLBs::stopPretendingHostRAMisDeallocated() {
    if (mDMABufferPretendDeleted) {
      mDMABufferPretendDeleted = false;
      mPinnedHostBuf.size = 0u; // finally record the allocation gone
    }
  }
  
  LogCarStorage::LogCar * OurTLBs::getLogCarHost(u32 tlbi, u32 carnum) {
    MFM_API_ASSERT_NONNULL(mMapAll);
    char * tlbBase = (((char*) mMapAll) + tlbi*AHAX_CONSTANT2M);
    u32 logcarsize = sizeof(MFM::LogCarStorage::LogCar);
    return (LogCarStorage::LogCar*) (tlbBase+carnum*logcarsize);
  }

  u32 OurTLBs::getLogCarT6(u32 tlbi, u32 carnum) {
    MFM_API_ASSERT_NONNULL(mMapAll);
    const TLBInfo & info = getTLBInfo(tlbi);
    u32 base = info.mLogTransportBlockStart; // WAS: MFM::T6::transportblock_log_start;
    u32 logcarsize = sizeof(MFM::LogCarStorage::LogCar);
    return base+carnum*logcarsize;
  }
    
  void OurTLBs::allocateTLBs() {

    // allocate our 2MB tlbs
    for (unsigned i = 0; i < AHAX_TLB2M_COUNT; ++i) {

      struct tenstorrent_allocate_tlb tlbio;
      tlbio.in.size = AHAX_CONSTANT2M;
      s32 ret = ioctl(mDevFD, TENSTORRENT_IOCTL_ALLOCATE_TLB, &tlbio);
      if (ret < 0) {
        perror("allocate TLB failed");
        ASSERT(ret >= 0);
      }
      mTLBInfos[i].mAllocOut = tlbio.out;

      /*
      if (i < 2u || i >= AHAX_TLB2M_COUNT-2u)
        LOGprintf(mDevCardNum,"TLBALLOC id=%u uc=0x%lx wc=0x%lx\n",
               mTLBInfos[i].mAllocOut.id,
               mTLBInfos[i].mAllocOut.mmap_offset_uc,
               mTLBInfos[i].mAllocOut.mmap_offset_wc);
      */
    }
  }

  void OurTLBs::deallocateTLBs() {

    // free the 2MB tlbs
    for (unsigned i = 0; i < AHAX_TLB2M_COUNT; ++i) {

      struct tenstorrent_free_tlb tlbio;
      tlbio.in.id = mTLBInfos[i].mAllocOut.id;
      s32 ret = ioctl(mDevFD, TENSTORRENT_IOCTL_FREE_TLB, &tlbio);
      if (ret < 0) {
        perror("free TLB failed");
        ASSERT(ret >= 0);
      }

      /*
      if (i < 2u || i >= AHAX_TLB2M_COUNT-2u)
        LOGprintf(mCardNum,"TLBFREE id=%u uc=0x%lx wc=0x%lx\n",
               mTLBInfos[i].mAllocOut.id,
               mTLBInfos[i].mAllocOut.mmap_offset_uc,
               mTLBInfos[i].mAllocOut.mmap_offset_wc);
      */
    }
    memset_s(mTLBInfos,0u,sizeof(mTLBInfos));
  }  

  void OurTLBs::configureTLBs() {
    // get addrs to cover all our needs
    mMapAll = mmap(NULL, AHAX_MMAP_SIZE, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    ASSERT(mMapAll != MAP_FAILED);
    LOGprintf(mDevCardNum,"MMAP AT %p\n", mMapAll);

    // configure and map all but the last two to the fleet - L1 uni
    for (unsigned i = AHAX_TLBI_L1_FIRST_UNI; i <= AHAX_TLBI_L1_LAST_UNI; ++i) {
      U16C nocc = U16C::makeNocCoordFromTLBI(i);

      // configure as T6/L1 access window
      void * ptr = configureL1Window(i,{nocc,nocc});

      /*
      if (i < 2u || i >= AHAX_TLB2M_COUNT-4u)
        LOGprintf(mCardNum,"TLBCFG %u @ (%u,%u) mapped at %p\n",i,nocc.x,nocc.y,ptr);
      */
      
    }
  
    // map last two
    {
      void * ptr = configureMulticastWindow(AHAX_TLBI_L1_MULTI, 0x0, /*wc=*/ true);
      //LOGprintf(mCardNum,"L1MULTI %u mapped at %p\n",AHAX_TLBI_L1_MULTI,ptr);
    }
    {
      void * ptr = configureMulticastWindow(AHAX_TLBI_DEBUG_MULTI, 0xFFB12000, false);
      //LOGprintf(mCardNum,"DEBUGMULTI %u mapped at %p\n",AHAX_TLBI_DEBUG_MULTI,ptr);
    }
  }

  void OurTLBs::unconfigureTLBs() {
    // release the TLB map
    s32 ret = munmap(mMapAll, AHAX_MMAP_SIZE);
    ASSERT(ret==0);

    // We believe there is nothing actually to do to 'unconfigure' the indiv TLBs?
  }  

  void OurTLBs::writeToWords(u32 tlbi, u32 destAddr, u32 * words, u32 wordCount) {
    u32 * tlbBase = (u32*) ((char*) mMapAll + tlbi*AHAX_CONSTANT2M);
    u32 * destTop = (u32*) (((u64) destAddr)&~((u64) AHAX_CONSTANT2M_MASK));
    u32 destOffsetWords = (destAddr&AHAX_CONSTANT2M_MASK)>>2u;
    if (destTop != (u32*) (((u64) mTLBInfos[tlbi].mRemoteBaseAddress)&~((u64) AHAX_CONSTANT2M_MASK)))
      HOST_FATAL(BAD_ALIGNMENT,
                 "TOP BIT MISMATCH FOR TLBI %d base %p top %p (from 0x%x, wanted 0x%x)\n",
                 tlbi,tlbBase,destTop,destAddr,destOffsetWords<<2u);
    for (u32 i = 0u; i < wordCount; ++i) {
      if (false && (i < 10u || i >= wordCount - 10u))
        LOGprintf(mDevCardNum,"WT %d/%d %p/0x%08x = 0x%08x\n",
               tlbi,i,
               (volatile uint32_t*)(tlbBase + destOffsetWords + i),
               destAddr+4u*i,
               words[i]);
      u32 ow = destOffsetWords+i;
      if (false && ow >= 0 && ow <= 8)
        Eprintf("(%u) da:%x+%dw WRITONG 0x%08x to 0x%x\n",
                tlbi, destAddr, wordCount, words[i], ow<<2);

      *(volatile uint32_t*)(tlbBase + destOffsetWords + i) = words[i];
    }
  }

  void OurTLBs::readFromWords(u32 tlbi, u32 srcByteAddr, u32 * words, u32 wordCount) {
    char * tlbBase = ((char*) mMapAll + tlbi*AHAX_CONSTANT2M);
    u32 srcTop = srcByteAddr&~AHAX_CONSTANT2M_MASK;
    u32 srcOffsetWords = srcByteAddr&AHAX_CONSTANT2M_MASK;
    if (srcTop != 0u)
      LOGprintf(mDevCardNum,"IGNORING TOP BITS FOR TLBI %d base %p top 0x%x (from 0x%x, using 0x%x)\n",
             tlbi,tlbBase,srcTop,srcByteAddr,srcOffsetWords<<2u);
    for (u32 i = 0u; i < wordCount; ++i) {
      words[i] = *(volatile uint32_t*)(tlbBase + srcOffsetWords + (i<<2u));
      if (false) {
        if (i < 20u || i >= wordCount - 20u)
          LOGprintf(mDevCardNum,"RF %d %p = 0x%08x (%d)\n",
                 i,(volatile uint32_t*)(tlbBase + srcOffsetWords + (i<<2u)),words[i],tlbi);
      }
    }
  }
  
  void * OurTLBs::configureMulticastWindow(u32 tlbi, u32 address, bool wc) {
    return configureWindow(tlbi, {{1,2},{16,11}}, address, wc);
    //return configureWindow(tlbi, {{1,2},{1,11}}, address, wc);
  }

  void * OurTLBs::configureL1Window(u32 tlbi, U16CRange range) {
    return configureWindow(tlbi, range, 0u, true);
  }

  OurTLBs::TLBInfo & OurTLBs::getTLBInfo(u32 tlbi) {
    MFM_API_ASSERT(tlbi < AHAX_TLB2M_COUNT, ARRAY_INDEX_OUT_OF_BOUNDS);
    return mTLBInfos[tlbi];
  }

  void OurTLBs::TLBInfo::setDeployedImage(const T6Image & img) {
    mDeployedImage = &img;
    {
      ImageBlockAddr * ibap = img.getImageBlockAddrForBlockCodeIfAny(BlockCode::BC_LOGCARS);
      if (ibap && ibap->isValid()) {
        mLogTransportBlockStart = ibap->getBlockAddr();
      } else {
        mLogTransportBlockStart = 0u;
      }
    }
    {
      ImageBlockAddr * ibap = img.getImageBlockAddrForBlockCodeIfAny(BlockCode::BC_EWCARS);
      if (ibap && ibap->isValid()) {
        mEWTransportBlockStart = ibap->getBlockAddr();
      } else {
        mEWTransportBlockStart = 0u;
      }
    }
  }
  

  void * OurTLBs::configureWindow(u32 tlbi, U16CRange range, u32 address, bool wc) {
    unsigned ismulti = range.area() > 1u;
    //LOGprintf(mCardNum,"CWD %d, %d (%d,%d) (%d,%d)\n",tlbi,ismulti,range.end.x,range.end.y,range.start.x,range.start.y);
    struct tenstorrent_configure_tlb confio;
    memset_s(&confio,0,sizeof(confio));
    struct tenstorrent_configure_tlb_in & cfin = confio.in;
    struct tenstorrent_configure_tlb_out & cfout = confio.out;

    cfin.id = mTLBInfos[tlbi].mAllocOut.id;
    mTLBInfos[tlbi].mRemoteBaseAddress = address;
    struct tenstorrent_noc_tlb_config & cfnoc = cfin.config;
    cfnoc.addr = address&~AHAX_CONSTANT2M_MASK; // window starting address in (x,y) space?
    cfnoc.x_end = range.end.x;
    cfnoc.y_end = range.end.y;
    cfnoc.x_start = range.start.x;     // need start and end for unicast?
    cfnoc.y_start = range.start.y;
    cfnoc.noc = 0u;
    cfnoc.mcast = ismulti;
    // cfnoc.ordering = 0u; // ??? 1 == strict? 0 == relaxed?
    // cfnoc.linked
    // cfnoc.static_vc
    
    ASSERT(ioctl(mDevFD, TENSTORRENT_IOCTL_CONFIGURE_TLB, &confio) >= 0);

    // map window into our space
    u64 offset = wc ?
      mTLBInfos[tlbi].mAllocOut.mmap_offset_wc :
      mTLBInfos[tlbi].mAllocOut.mmap_offset_uc;
    void * ptr;
    if ((ptr = mmap((void*)(((char*) mMapAll) + tlbi*AHAX_CONSTANT2M), AHAX_CONSTANT2M,
                    PROT_READ | PROT_WRITE, MAP_SHARED | MAP_FIXED,
                    mDevFD, offset)) == MAP_FAILED)
      HOST_FATAL(OPERATION_FAILED,"MMAP FAIL");

    return ptr;
  }

  void OurTLBs::updateLogCars(unsigned tlbi) {
    pinned_host_buffer_t& buf = mPinnedHostBuf;
    void * hostmem = buf.host_ptr;
    u64 hostnocaddr = buf.noc_addr;

    u32 t6offset = tlbi * mT6BufferSize;
    void * pert6addr = ((char*)hostmem) + t6offset;

    BHLog & bhl = BHLog::getTheBHLog();

    LogCarStorage & stg = *(LogCarStorage*) pert6addr;
    TLBInfo & tin = getTLBInfo(tlbi);
    for (u32 tries = 0u; tries < LogCarStorage::CAR_COUNT; ++tries) {
      u32 car = tin.getLogCarIndex();
      LogCarStorage::LogCar & lc = stg.mLogCars[car];
      CarSig cs = lc.getHeader();

      U16C addr = U16C::makeNocCoordFromTLBI(tlbi);
      if (lc.isComplete() && lc.getCarState() == CarState::INBOUND_DEPARTED) {
        CarSig cs = lc.getHeader();
        LogBlock & lb = lc.getContent();

        if (cs.mCarType == CarType::STANDARD) {
          
          BHTag tag(TagType::T6TADR,mDevCardNum,addr.x,addr.y);

          if (false)
            Eprintf("(%u) INBOUND TRAFFIC FROM T%d (%d,%d) %d bytes\n",
                    bhl.getThrId(), tlbi, addr.x, addr.y, lb.mLength);

          {                     // deal with the passengers
            FILE* log = getHostLogForKey(tag);
            fprintf(log,"[#%d]",car);
            fwrite((const char *) lb.mData,lb.mLength,1u,log);
            fclose(log);
          }

          //KTEEwrite(tag, lb.mData, lb.mLength);
        }
          
        lb.reset();           // clean the car (even if it was officially empty?)
        lc.setCarState(CarState::OUTBOUND_DEPARTED,CarType::EMPTY); // ship an empty
        { // APPARENTLY IT'S TIME TO ACTUALLY SHIP THIS MOFO
          u32 destByteAddr = tin.mLogTransportBlockStart + car * sizeof(lc);
          // empty case is 2 words only - header + footer
          if (true) // but for now let's NOT not and say we did
            writeToWords(tlbi, destByteAddr, (u32*) &lc, 2u); 
          if (false)
            Eprintf("(%u) RETURNING EMPTY TO T%d 0x%08x @ (%d,%d)\n\n",
                    bhl.getThrId(),
                    tlbi,
                    destByteAddr,
                    addr.x, addr.y);
        } 
      }
      tin.advanceLogCarIndex(); // check next car
    }
  }

  void OurTLBs::updateEWCars(unsigned tlbi) {
    TLBInfo & info = getTLBInfo(tlbi);
    const T6Image * image = info.getDeployedImageIfAny();

    // Only send events to actual images..
    if (!image) {
      Eprintf("EW skipping %u - no image\n",tlbi);
      return;
    }
    // ..that have BC_EWCARS blocks
    if (info.mEWTransportBlockStart == 0u) {
      Eprintf("EW skipping %u - EW cars\n",tlbi);
      return;
    }

    /*
    Eprintf("EW GO on %u vs %u\n", image->getImageCode(), ImageCode::IC_EWP);
    if (image->getImageCode() != ImageCode::IC_EWP) {
      Eprintf("EW mism %u != %u\n", image->getImageCode(), ImageCode::IC_EWP);
      return;
    }
    */

    
    pinned_host_buffer_t& buf = mPinnedHostBuf;
    void * hostmem = buf.host_ptr;
    u64 hostnocaddr = buf.noc_addr;

    u32 t6offset = tlbi * mT6BufferSize + info.mEWTransportBlockStart; 
    void * pert6addr = ((char*)hostmem) + t6offset;

    EWCarStorage & stg = *(EWCarStorage*) pert6addr;
    EWControl & ewc = EWControl::getTheEWControl();
    
    for (u32 car = 0u; car < EWCarStorage::CAR_COUNT; ++car) {
      EWCarStorage::EWCar & ec = stg.mEWCars[car];
      EWBlock & eb = ec.getContent();
      CarSig cs = ec.getHeader();

      if (ec.getCarState() == CarState::UNUSED) { 
        // start with all EW cars host side
        ec.setCarState(CarState::OPEN, CarType::STANDARD);
        continue;
      }

      U16C addr = U16C::makeNocCoordFromTLBI(tlbi);
      if (!ec.isComplete()) {
        static u32 loops = 0;
        if ((loops++ % 1000) == 0)
          LOGprintf(mDevCardNum,"<%d> INCOM? %u #%d@(%d,%d)!\n",
                    mDevCardNum, loops, car, addr.x, addr.y);
        continue;
      }

      if (ec.getCarState() == CarState::INBOUND_DEPARTED) {
        // Welcome To Host Central, The Centraliest Center Around

        CarSig cs = ec.getHeader();

        if (cs.mCarType != CarType::STANDARD) FAIL(UNSUPPORTED_OPERATION);
          
        BHTag tag(TagType::T6TADR,mDevCardNum,addr.x,addr.y);

        /// TRY TO COMMIT RETURNED EW
        ++mEWsReturned;

        if (false)
          LOGprintf(mDevCardNum,"<%d> RECEIVINGEW s%d/r%d/c%d from #%d@(%d,%d)!\n",
                    mDevCardNum, mEWsShipped,mEWsReturned,mEWsCommitted, car,
                    addr.x, addr.y);
        s32 status;
        if ((status = ewc.tryCommitEWCar(tag,ec))==0) ++mEWsCommitted;
        if (false)
          LOGprintf(mDevCardNum,"<%d> bop%d (%d,%d)\n",
                    mDevCardNum, status, addr.x, addr.y);
        ec.setCarState(CarState::OPEN,CarType::STANDARD); 
        continue;
      }
      
      if (ec.getCarState() == CarState::OPEN) {
        //// HANDLE FILLING AN OUTBOUND EW
        static u32 loops = 0u;
        constexpr u32 PERIOD = 100'000u;

        EWBlock & eb = ec.getContent();
        if (ewc.tryLoadEWCar(ec)) {

          if ((loops++ % PERIOD) == 0u) {
            LOGprintf(mDevCardNum,"<BH:%d> %u OPNLODE EW#%d[%d,%d] @ %d (%d,%d)!\n",
                      mDevCardNum,
                      loops/PERIOD,
                      car, 
                      eb.mHiddenXPos,
                      eb.mHiddenYPos,
                      tlbi, addr.x, addr.y);
          }

          {
            P4Atom a = eb.mOld.getAtom(0u);
            if (a.getType() == P4Atom::START_TYPE)
              Eprintf("<BH:%d> CLOSEEWSTART (%d,%d) ts=%f to noc(%u,%u)\n",
                      mDevCardNum,
                      eb.mHiddenXPos, eb.mHiddenYPos,
                      secondsSinceStart(eb.mSTVLTime),
                      addr.x, addr.y);
          }

          ec.setCarState(CarState::CLOSED,CarType::STANDARD);
        }
        continue;
      }

      if (ec.getCarState() == CarState::CLOSED) {
        // IT'S TIME TO SHIP THIS MOFO
        // BUT ONLY IF WE'RE EVENT WINDOWS ACTIVE
        if (!ewc.isActive()) {
          Eprintf("<BlackHole:%d> tlbi%u: want to ship but not active\n",
                  mDevCardNum, tlbi);
        } else /*ewc.isActive()*/ {
          ec.setCarState(CarState::OUTBOUND_DEPARTED,CarType::STANDARD); 

          u32 destByteAddr = info.mEWTransportBlockStart + car * sizeof(ec);

          writeToWords(tlbi, destByteAddr, (u32*) &ec, sizeof(ec)>>2); 
          {
            P4Atom a = eb.mOld.getAtom(0u);
            if (a.getType() == P4Atom::START_TYPE) {
              Eprintf("<BH:%d> SHIPTEWSTART (%d,%d) ts=%f to noc(%u,%u)\n",
                      mDevCardNum,
                      eb.mHiddenXPos, eb.mHiddenYPos,
                      secondsSinceStart(eb.mSTVLTime),
                      addr.x, addr.y);
              LOGprintf(mDevCardNum,"<BlackHole:%d> %d SHIPPING EW#%d(%d) TO [0x%08x..0x%08x) @ %d (%d,%d)!\n",
                        mDevCardNum, mEWsShipped,
                        car, ec.getCarState(),
                        destByteAddr, destByteAddr+sizeof(ec),
                        tlbi, addr.x, addr.y);
            }
          }          
          ++mEWsShipped;
        }
        continue;
      }
      if (ec.getCarState() == CarState::OUTBOUND_DEPARTED) {
        static u32 loops = 0;
        constexpr u32 MAX=1'000'000'000u;
        if ((loops++ % MAX) == 0u)
          LOGprintf(mDevCardNum,"<BlackHole:%d> ML%u WAITING ON CAR %d @ %d (%d,%d)!\n",
                    mDevCardNum, loops/MAX, car, tlbi, addr.x, addr.y);
        continue;
      }
      LOGprintf(mDevCardNum,"<BlackHole:%d> WHAT TYPE? %d @ %d (%d,%d)!\n",
                mDevCardNum, ec.getCarState(), tlbi, addr.x, addr.y);
    }
  }

  bool OurTLBs::updateTransports(bool includeEWs) {
    for (unsigned tlbi = AHAX_TLBI_L1_FIRST_UNI; tlbi <= AHAX_TLBI_L1_LAST_UNI; ++tlbi) {
      updateLogCars(tlbi);
      if (includeEWs) updateEWCars(tlbi);
    }
    //XXX BURN BABY BURNNNNN:
    sleepUsec(10);
    return true;
  }

  void OurTLBs::resetTheFleet() {
    // Everybody into soft reset
    write32(MFM::OurTLBs::AHAX_TLBI_DEBUG_MULTI,
            RISCV_DEBUG_REG_SOFT_RESET_0,
            SOFT_RESET_ALL_RISCV);

    // Set everybody's per-hart starting addresses
    const MFM::u32 data[][2] = {
      {RISCV_DEBUG_REG_TRISC0_RESET_PC, 4u},
      {RISCV_DEBUG_REG_TRISC1_RESET_PC, 8u},
      {RISCV_DEBUG_REG_TRISC2_RESET_PC, 12u},
      {RISCV_DEBUG_REG_NCRISC_RESET_PC, 16u},
      {RISCV_DEBUG_REG_TRISC_RESET_PC_OVERRIDE, 0x1|0x2|0x4}, // use custom start addrs for T0,T1,T2
      {RISCV_DEBUG_REG_NCRISC_RESET_PC_OVERRIDE, 0x1},        // use custom start addr for NCRISC
    };

    for (MFM::u32 i = 0u; i < sizeof(data)/sizeof(data[0]); ++i) {
      write32(MFM::OurTLBs::AHAX_TLBI_DEBUG_MULTI, data[i][0], data[i][1]);
    }

#if 0 // Can't read from RISCV_DEBUG addrs (0xffb1'0000+) using L1 TLBs (0x0..0x0020'0000)
    for (unsigned tlbi = AHAX_TLBI_L1_FIRST_UNI; tlbi <= AHAX_TLBI_L1_LAST_UNI; ++tlbi) {

      for (MFM::u32 i = 0u; i < sizeof(data)/sizeof(data[0]); ++i) {
        u32 readback = read32(tlbi,data[i][0]);
        if (readback != data[i][1])
          Eprintf("<BlackHole:%d> tlbi%u: readback failure @ 0x%08x: wanted 0x%08x, got 0x%08x\n",
                  mDevCardNum, tlbi, data[i][0],
                  data[i][1], readback);
      }
    }
#endif    
  }

}
