#ifndef CONSTANTS_H
#define CONSTANTS_H

/*
 * SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <unistd.h>

#if defined(MAP_ANON) && !defined(MAP_ANONYMOUS)
#define MAP_ANONYMOUS MAP_ANON
#endif

// Inlined copy of what we need from https://github.com/tenstorrent/tt-kmd/blob/main/ioctl.h:

#define TENSTORRENT_IOCTL_GET_DEVICE_INFO   0xFA00
#define TENSTORRENT_IOCTL_QUERY_MAPPINGS    0xFA02
#define TENSTORRENT_IOCTL_ALLOCATE_TLB      0xFA0B

#define TENSTORRENT_MAPPING_RESOURCE0_UC 1

#define PCI_VENDOR_ID_TENSTORRENT 0x1E52
#define PCI_DEVICE_ID_BLACKHOLE	  0xB140

#define TLB_CONFIG_ADDR         0x1FC00000
#define TLB_CONFIG_ADDR_STRIDES 0x1FC009D8
#define TLB_CONFIG_ADDR_END     0x1FC00A58

// RISCV Code entry points:

#define RISCV_DEBUG_REG_SOFT_RESET_0             0xFFB121B0
#define RISCV_DEBUG_REG_TRISC0_RESET_PC          0xFFB12228
#define RISCV_DEBUG_REG_TRISC1_RESET_PC          0xFFB1222C
#define RISCV_DEBUG_REG_TRISC2_RESET_PC          0xFFB12230
#define RISCV_DEBUG_REG_TRISC_RESET_PC_OVERRIDE  0xFFB12234
#define RISCV_DEBUG_REG_NCRISC_RESET_PC          0xFFB12238
#define RISCV_DEBUG_REG_NCRISC_RESET_PC_OVERRIDE 0xFFB1223C

#define SOFT_RESET_ALL_RISCV 0x047800

// Memory map stuff

/////////////
// RISC-V Address map definition (hardware)

// TODO: Consider redefining these as uint32_t rather then #defines

// Reads and writes here access the tensix core register set. Each register is four bytes, but subword reads are
// supported through byte enables. Register indices and contents are defined in local_regs.yaml.
#define REGFILE_BASE 0xFFE00000  // 0xFFE00000 - 0xFFE3FFFF

// PC buffer is used to pass kernel IDs and parameters from Brisc to Triscs, and also as a sync point -- a read from pc
// buffer+1 address will not return until that thread is idle.
#define PC_BUF_BASE 0xFFE80000   // 0xFFE80000 - 0xFFEBFFFF
#define PC1_BUF_BASE 0xFFE90000  // 0xFFE80000 - 0xFFEBFFFF
#define PC2_BUF_BASE 0xFFEA0000

// Reads from here retrieve a value written by the tensix code, or 0 if there the mailbox FIFO is empty.
#define TENSIX_MAILBOX0_BASE 0xFFEC0000  // Brisc
#define TENSIX_MAILBOX1_BASE 0xFFEC1000  // Trisc0
#define TENSIX_MAILBOX2_BASE 0xFFEC2000  // Trisc1
#define TENSIX_MAILBOX3_BASE 0xFFEC3000  // Trisc2

// Config registers
#define TENSIX_CFG_BASE 0xFFEF0000  // 0xFFEF0000 - 0xFFF00000

// MOP config registers
#define TENSIX_MOP_CFG_BASE 0xFFB80000  // 0xFFB8000 - 0xFFB8100

// TDMA register base
#define RISCV_TDMA_REGS_START_ADDR 0xFFB11000
#define RISCV_TDMA_REG_XMOV_SRC_ADDR 0xFFB11000
#define RISCV_TDMA_REG_XMOV_DST_ADDR 0xFFB11004
#define RISCV_TDMA_REG_XMOV_SIZE 0xFFB11008
#define RISCV_TDMA_REG_XMOV_DIRECTION 0xFFB1100C
#define RISCV_TDMA_REG_COMMAND_ADDR 0xFFB11010
#define RISCV_TDMA_REG_STATUS 0xFFB11014
#define RISCV_TDMA_REG_PACKED_SIZE 0xFFB11018
#define RISCV_TDMA_REG_ACC_PACKED_SIZE 0xFFB1101C   // read only
#define RISCV_TDMA_REG_INITIAL_PACK_ACC 0xFFB1101C  // write only
#define RISCV_TDMA_REG_CLK_GATE_EN 0xFFB11024
#define RISCV_TDMA_REG_CLK_GATE_HYST 0xFFB11028
#define RISCV_TDMA_REG_XMOV_L1_BASE_ADDR 0xFFB1102C
#define RISCV_TDMA_REG_FIFO_PACKED_TILE_SIZE(packer) (0xFFB11030 | (packer << 8))
#define RISCV_TDMA_REG_FIFO_PACKED_TILE_ZEROMASK(packer) (0xFFB11034 | (packer << 8))
#define RISCV_TDMA_REG_FIFO_PACKED_TILE_STATUS (0xFFB11038)

#define RISCV_TDMA_PACKED_TILE_FIFO_EMPTY(status, packer) ((status >> (packer * 2)) & 0x1)
#define RISCV_TDMA_PACKED_TILE_FIFO_FULL(status, packer) ((status >> (packer * 2 + 1)) & 0x1)
#define RISCV_TDMA_STATUS_FLAG_MOVER0_BUSY_MASK 0x01
#define RISCV_TDMA_STATUS_FLAG_MOVER1_BUSY_MASK 0x02
#define RISCV_TDMA_STATUS_FLAG_FIFO_FULL_MASK 0x04
#define RISCV_TDMA_STATUS_FLAG_FIFO_EMPTY_MASK 0x08
#define RISCV_TDMA_STATUS_FLAG_ERROR_MASK 0x10

#define RISCV_SOFT_RESET_0_NONE 0x00000
#define RISCV_SOFT_RESET_0_BRISC 0x00800
#define RISCV_SOFT_RESET_0_NCRISC 0x40000
#define RISCV_SOFT_RESET_0_TRISCS 0x07000

// Debug registers
/*
#!/usr/bin/env lua

-- Stupid little helper to generate the defines shown below

root = assert(os.getenv("ROOT"), "Must provide ROOT env var porinting to repo root")
f = assert(io.open(root .. "/src/hardware/tensix/rtl/tt_risc_debug_regs.sv"))

f = f:read("*a")

for nm,addr in f:gmatch("localparam%s*([a-zA-Z0-9_]*)%s*=%s*32'h(%x*)%s*;") do
    io.write"#define RISCV_DEBUG_REG_"
    io.write(nm)
    local num = 40 - #nm
    if num < 0 then num = 0 end
    local pad = string.rep(" ", num)
    io.write(pad)
    io.write"(RISCV_DEBUG_REGS_START_ADDR | 0x"
    io.write(addr)
    io.write")\n"
end
*/
#define RISCV_DEBUG_REGS_START_ADDR 0xFFB12000
#define RISCV_DEBUG_REG_PERF_CNT_INSTRN_THREAD0 (RISCV_DEBUG_REGS_START_ADDR | 0x0)
#define RISCV_DEBUG_REG_PERF_CNT_INSTRN_THREAD1 (RISCV_DEBUG_REGS_START_ADDR | 0x4)
#define RISCV_DEBUG_REG_PERF_CNT_INSTRN_THREAD2 (RISCV_DEBUG_REGS_START_ADDR | 0x8)
#define RISCV_DEBUG_REG_PERF_CNT_TDMA_UNPACK0 (RISCV_DEBUG_REGS_START_ADDR | 0xC)
#define RISCV_DEBUG_REG_PERF_CNT_TDMA_UNPACK1 (RISCV_DEBUG_REGS_START_ADDR | 0x10)
#define RISCV_DEBUG_REG_PERF_CNT_TDMA_UNPACK2 (RISCV_DEBUG_REGS_START_ADDR | 0x14)
#define RISCV_DEBUG_REG_PERF_CNT_FPU0 (RISCV_DEBUG_REGS_START_ADDR | 0x18)
#define RISCV_DEBUG_REG_PERF_CNT_FPU1 (RISCV_DEBUG_REGS_START_ADDR | 0x1C)
#define RISCV_DEBUG_REG_PERF_CNT_FPU2 (RISCV_DEBUG_REGS_START_ADDR | 0x20)
#define RISCV_DEBUG_REG_PERF_CNT_L1_0 (RISCV_DEBUG_REGS_START_ADDR | 0x30)
#define RISCV_DEBUG_REG_PERF_CNT_L1_1 (RISCV_DEBUG_REGS_START_ADDR | 0x34)
#define RISCV_DEBUG_REG_PERF_CNT_L1_2 (RISCV_DEBUG_REGS_START_ADDR | 0x38)
#define RISCV_DEBUG_REG_PERF_CNT_ALL (RISCV_DEBUG_REGS_START_ADDR | 0x3C)
#define RISCV_DEBUG_REG_DBG_L1_MEM_REG0 (RISCV_DEBUG_REGS_START_ADDR | 0x48)
#define RISCV_DEBUG_REG_DBG_L1_MEM_REG1 (RISCV_DEBUG_REGS_START_ADDR | 0x4C)
#define RISCV_DEBUG_REG_DBG_L1_MEM_REG2 (RISCV_DEBUG_REGS_START_ADDR | 0x50)
#define RISCV_DEBUG_REG_DBG_BUS_CTRL (RISCV_DEBUG_REGS_START_ADDR | 0x54)
#define RISCV_DEBUG_REG_TENSIX_CREG_READ (RISCV_DEBUG_REGS_START_ADDR | 0x58)
#define RISCV_DEBUG_REG_DBG_RD_DATA (RISCV_DEBUG_REGS_START_ADDR | 0x5C)
#define RISCV_DEBUG_REG_THREAD1_CREG_READ (RISCV_DEBUG_REGS_START_ADDR | 0x5C)
#define RISCV_DEBUG_REG_DBG_ARRAY_RD_EN (RISCV_DEBUG_REGS_START_ADDR | 0x60)
#define RISCV_DEBUG_REG_DBG_ARRAY_RD_CMD (RISCV_DEBUG_REGS_START_ADDR | 0x64)
#define RISCV_DEBUG_REG_DBG_FEATURE_DISABLE (RISCV_DEBUG_REGS_START_ADDR | 0x68)
#define RISCV_DEBUG_REG_DBG_ARRAY_RD_DATA (RISCV_DEBUG_REGS_START_ADDR | 0x6C)
#define RISCV_DEBUG_REG_CG_CTRL_HYST0 (RISCV_DEBUG_REGS_START_ADDR | 0x70)
#define RISCV_DEBUG_REG_CG_CTRL_HYST1 (RISCV_DEBUG_REGS_START_ADDR | 0x74)
#define RISCV_DEBUG_REG_TENSIX_CREG_RDDATA (RISCV_DEBUG_REGS_START_ADDR | 0x78)
#define RISCV_DEBUG_REG_CG_CTRL_HYST2 (RISCV_DEBUG_REGS_START_ADDR | 0x7C)
#define RISCV_DEBUG_REG_THREAD1_CREG_RDDATA (RISCV_DEBUG_REGS_START_ADDR | 0x7C)
#define RISCV_DEBUG_REG_RISC_DBG_CNTL_0 (RISCV_DEBUG_REGS_START_ADDR | 0x80)
#define RISCV_DEBUG_REG_RISC_DBG_CNTL_1 (RISCV_DEBUG_REGS_START_ADDR | 0x84)
#define RISCV_DEBUG_REG_RISC_DBG_STATUS_0 (RISCV_DEBUG_REGS_START_ADDR | 0x88)
#define RISCV_DEBUG_REG_RISC_DBG_STATUS_1 (RISCV_DEBUG_REGS_START_ADDR | 0x8C)
#define RISCV_DEBUG_REG_TRISC_PC_BUF_OVERRIDE (RISCV_DEBUG_REGS_START_ADDR | 0x90)
#define RISCV_DEBUG_REG_DBG_INVALID_INSTRN (RISCV_DEBUG_REGS_START_ADDR | 0x94)
#define RISCV_DEBUG_REG_DBG_INSTRN_BUF_CTRL0 (RISCV_DEBUG_REGS_START_ADDR | 0xA0)
#define RISCV_DEBUG_REG_DBG_INSTRN_BUF_CTRL1 (RISCV_DEBUG_REGS_START_ADDR | 0xA4)
#define RISCV_DEBUG_REG_DBG_INSTRN_BUF_STATUS (RISCV_DEBUG_REGS_START_ADDR | 0xA8)
#define RISCV_DEBUG_REG_STOCH_RND_MASK0 (RISCV_DEBUG_REGS_START_ADDR | 0xAC)
#define RISCV_DEBUG_REG_STOCH_RND_MASK1 (RISCV_DEBUG_REGS_START_ADDR | 0xB0)
#define RISCV_DEBUG_REG_FPU_STICKY_BITS (RISCV_DEBUG_REGS_START_ADDR | 0xB4)
#define RISCV_DEBUG_REG_ETH_RISC_PREFECTH_CTRL (RISCV_DEBUG_REGS_START_ADDR | 0xB8)
#define RISCV_DEBUG_REG_ETH_RISC_PREFECTH_PC (RISCV_DEBUG_REGS_START_ADDR | 0xBC)
#define RISCV_DEBUG_REG_PERF_CNT_TDMA_PACK0 (RISCV_DEBUG_REGS_START_ADDR | 0xF0)
#define RISCV_DEBUG_REG_PERF_CNT_TDMA_PACK1 (RISCV_DEBUG_REGS_START_ADDR | 0xF4)
#define RISCV_DEBUG_REG_PERF_CNT_TDMA_PACK2 (RISCV_DEBUG_REGS_START_ADDR | 0xF8)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_L_INSTRN_THREAD (RISCV_DEBUG_REGS_START_ADDR | 0x100)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_H_INSTRN_THREAD (RISCV_DEBUG_REGS_START_ADDR | 0x104)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_L_TDMA_UNPACK (RISCV_DEBUG_REGS_START_ADDR | 0x108)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_H_TDMA_UNPACK (RISCV_DEBUG_REGS_START_ADDR | 0x10C)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_L_TDMA_PACK (RISCV_DEBUG_REGS_START_ADDR | 0x110)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_H_TDMA_PACK (RISCV_DEBUG_REGS_START_ADDR | 0x114)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_L_DBG_L1 (RISCV_DEBUG_REGS_START_ADDR | 0x118)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_H_DBG_L1 (RISCV_DEBUG_REGS_START_ADDR | 0x11C)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_L_FPU (RISCV_DEBUG_REGS_START_ADDR | 0x120)
#define RISCV_DEBUG_REG_PERF_CNT_OUT_H_FPU (RISCV_DEBUG_REGS_START_ADDR | 0x124)
#define RISCV_DEBUG_REG_SOFT_RESET_0 (RISCV_DEBUG_REGS_START_ADDR | 0x1B0)
#define RISCV_DEBUG_REG_ECC_CTRL (RISCV_DEBUG_REGS_START_ADDR | 0x1D0)
#define RISCV_DEBUG_REG_ECC_STATUS (RISCV_DEBUG_REGS_START_ADDR | 0x1D4)
#define RISCV_DEBUG_REG_WATCHDOG_TIMER (RISCV_DEBUG_REGS_START_ADDR | 0x1E0)
#define RISCV_DEBUG_REG_WDT_CNTL (RISCV_DEBUG_REGS_START_ADDR | 0x1E4)
#define RISCV_DEBUG_REG_WDT_STATUS (RISCV_DEBUG_REGS_START_ADDR | 0x1E8)
#define RISCV_DEBUG_REG_WALL_CLOCK_0 (RISCV_DEBUG_REGS_START_ADDR | 0x1F0)
#define RISCV_DEBUG_REG_WALL_CLOCK_1 (RISCV_DEBUG_REGS_START_ADDR | 0x1F4)
#define RISCV_DEBUG_REG_WALL_CLOCK_1_AT (RISCV_DEBUG_REGS_START_ADDR | 0x1F8)
#define RISCV_DEBUG_REG_TIMESTAMP_DUMP_CMD (RISCV_DEBUG_REGS_START_ADDR | 0x1FC)
#define RISCV_DEBUG_REG_TIMESTAMP_DUMP_CNTL (RISCV_DEBUG_REGS_START_ADDR | 0x200)
#define RISCV_DEBUG_REG_TIMESTAMP_DUMP_STATUS (RISCV_DEBUG_REGS_START_ADDR | 0x204)
#define RISCV_DEBUG_REG_TIMESTAMP_DUMP_BUF0_START_ADDR (RISCV_DEBUG_REGS_START_ADDR | 0x208)
#define RISCV_DEBUG_REG_TIMESTAMP_DUMP_BUF0_END_ADDR (RISCV_DEBUG_REGS_START_ADDR | 0x20C)
#define RISCV_DEBUG_REG_TIMESTAMP_DUMP_BUF1_START_ADDR (RISCV_DEBUG_REGS_START_ADDR | 0x210)
#define RISCV_DEBUG_REG_TIMESTAMP_DUMP_BUF1_END_ADDR (RISCV_DEBUG_REGS_START_ADDR | 0x214)
#define RISCV_DEBUG_REG_PERF_CNT_MUX_CTRL (RISCV_DEBUG_REGS_START_ADDR | 0x218)
#define RISCV_DEBUG_REG_DBG_L1_READBACK_OFFSET (RISCV_DEBUG_REGS_START_ADDR | 0x21C)
#define RISCV_DEBUG_REG_LFSR_HIT_MASK (RISCV_DEBUG_REGS_START_ADDR | 0x220)
#define RISCV_DEBUG_REG_DISABLE_RESET (RISCV_DEBUG_REGS_START_ADDR | 0x224)
#define RISCV_DEBUG_REG_TRISC0_RESET_PC (RISCV_DEBUG_REGS_START_ADDR | 0x228)
#define RISCV_DEBUG_REG_TRISC1_RESET_PC (RISCV_DEBUG_REGS_START_ADDR | 0x22C)
#define RISCV_DEBUG_REG_TRISC2_RESET_PC (RISCV_DEBUG_REGS_START_ADDR | 0x230)
#define RISCV_DEBUG_REG_TRISC_RESET_PC_OVERRIDE (RISCV_DEBUG_REGS_START_ADDR | 0x234)
#define RISCV_DEBUG_REG_NCRISC_RESET_PC (RISCV_DEBUG_REGS_START_ADDR | 0x238)
#define RISCV_DEBUG_REG_NCRISC_RESET_PC_OVERRIDE (RISCV_DEBUG_REGS_START_ADDR | 0x23C)
#define RISCV_DEBUG_REG_DEST_CG_CTRL (RISCV_DEBUG_REGS_START_ADDR | 0x240)
#define RISCV_DEBUG_REG_CG_CTRL_EN (RISCV_DEBUG_REGS_START_ADDR | 0x244)
#define RISCV_DEBUG_REG_CG_KICK (RISCV_DEBUG_REGS_START_ADDR | 0x248)



#endif /* CONSTANTS_H */
