# GenerateFileIDs.cmake

function(generate_file_ids_header output_header_file)
  # Define the absolute path where the header will be generated *in this build context*.
  # If this is the primary build, this will be the canonical location.
  set(LOCAL_GENERATED_HEADER_PATH "${CMAKE_BINARY_DIR}/${output_header_file}")

  # Debugging messages
  message(STATUS "DEBUG: CMAKE_SOURCE_DIR: ${CMAKE_SOURCE_DIR}")
  message(STATUS "DEBUG: CMAKE_BINARY_DIR: ${CMAKE_BINARY_DIR}")
  message(STATUS "DEBUG: CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
  message(STATUS "DEBUG: CMAKE_CURRENT_BINARY_DIR: ${CMAKE_CURRENT_BINARY_DIR}")
  message(STATUS "DEBUG: PRIMARY_CMAKE_RUNNING (cache): ${PRIMARY_CMAKE_RUNNING}")
  message(STATUS "DEBUG: EXTERNAL_FILE_IDS_HEADER_DIR (cache): ${EXTERNAL_FILE_IDS_HEADER_DIR}")
  message(STATUS "DEBUG: Local generated header path for this build context: '${LOCAL_GENERATED_HEADER_PATH}'")

  # Only generate if PRIMARY_CMAKE_RUNNING is TRUE
  if(PRIMARY_CMAKE_RUNNING)
    message(STATUS "DEBUG: This is the PRIMARY build context. GENERATING FileIDs.h.")

    set(ALL_SOURCE_FILES "")

    # Collect .cpp and .h files recursively
    set(FILEID_ROOT_PATH "${CMAKE_SOURCE_DIR}/srcs")
    message(STATUS "AHAX: SEARCHING FOR FileID TARGETS IN ${FILEID_ROOT_PATH}")
  
    file(GLOB_RECURSE ALL_SOURCE_FILES CONFIGURE_DEPENDS
      "${FILEID_ROOT_PATH}/*.cpp"
      "${FILEID_ROOT_PATH}/*.h"
      "${FILEID_ROOT_PATH}/*.tcc"
      "${FILEID_ROOT_PATH}/*.S"
    )

    # Sort the list for consistent ID assignment across builds
    list(SORT ALL_SOURCE_FILES)

    set(FILE_ID_LINES "")
    set(current_id 1)   # SKIP ZERO FOR OoB

    #set(EXTRA_PATH_PREFIX ${CMAKE_PROJECT_NAME})  # see cross/toolchain-cross.cmake -macro-prefix-map
    set(EXTRA_PATH_PREFIX "")  # see cross/toolchain-cross.cmake -macro-prefix-map

    foreach(file_path IN LISTS ALL_SOURCE_FILES)
      # Normalize path to be relative to CMAKE_SOURCE_DIR for consistency
      file(RELATIVE_PATH relative_path "${CMAKE_SOURCE_DIR}" "${file_path}")
      string(APPEND FILE_ID_LINES " XX(\"${EXTRA_PATH_PREFIX}/${relative_path}\", ${current_id}) \\\n")
      math(EXPR current_id "${current_id} + 1")
    endforeach()

    # Generate the header file content
    set(HEADER_CONTENT "
#ifndef GENERATED_FILE_IDS_H
#define GENERATED_FILE_IDS_H

// Automatically generated by CMake. Do not edit.

#include \"utils.h\"

#define FILE_ID_LIST() \\
 XX(\" unused so 0 is OoB \", 0) \\
${FILE_ID_LINES}

#define XX(NAME,NUM) MFM::EQUAL_STRINGS(c,NAME) ? NUM : \

constexpr unsigned GET_FILE_ID(const char * c) {
  return
FILE_ID_LIST()
  0;
}
#undef XX

#define XX(NAME,NUM) (fileid == NUM) ? NAME : \

constexpr const char * GET_PATH_FROM_FILE_ID(unsigned fileid) {
  return 
FILE_ID_LIST()
  \"unknown\";
}
#undef XX

#endif // GENERATED_FILE_IDS_H
")

    # Write the content to the output header file
    file(WRITE "${LOCAL_GENERATED_HEADER_PATH}" "${HEADER_CONTENT}")

    # Add a custom command to ensure the header is generated during the build
    add_custom_command(
      OUTPUT "${LOCAL_GENERATED_HEADER_PATH}"
      COMMAND ${CMAKE_COMMAND} -D_HEADER_CONTENT="${HEADER_CONTENT}" -D_OUTPUT_FILE="${LOCAL_GENERATED_HEADER_PATH}" -P "${CMAKE_CURRENT_LIST_DIR}/write_file.cmake"
      DEPENDS ${ALL_SOURCE_FILES}
      COMMENT "Generating ${output_header_file} with file IDs"
    )
    # Create a dummy CMake script to write the file, as COMMAND expects an executable
    set(WRITE_FILE_SCRIPT_CONTENT "file(WRITE \"${_OUTPUT_FILE}\" \"${_HEADER_CONTENT}\")")
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/write_file.cmake" "${WRITE_FILE_SCRIPT_CONTENT}")

    # Store the path to the generated header's directory for targets in *this* build
    set(FILE_IDS_HEADER_DIR_FOR_THIS_BUILD "${CMAKE_BINARY_DIR}" PARENT_SCOPE)

  else()
    message(STATUS "DEBUG: This build context is NOT primary. It will use an external FileIDs.h.")
    # If not primary, we need to know where to find the externally generated header.
    if(DEFINED EXTERNAL_FILE_IDS_HEADER_DIR AND EXISTS "${EXTERNAL_FILE_IDS_HEADER_DIR}/${output_header_file}")
      set(FILE_IDS_HEADER_DIR_FOR_THIS_BUILD "${EXTERNAL_FILE_IDS_HEADER_DIR}" PARENT_SCOPE)
      message(STATUS "DEBUG: External FileIDs.h found at: ${EXTERNAL_FILE_IDS_HEADER_DIR}/${output_header_file}")
    else()
      message(FATAL_ERROR "ERROR: PRIMARY_CMAKE_RUNNING is OFF, but EXTERNAL_FILE_IDS_HEADER_DIR is not provided or FileIDs.h not found at expected path: ${EXTERNAL_FILE_IDS_HEADER_DIR}/${output_header_file}")
    endif()
  endif()
endfunction()
